const div1 = dom.Create('<div>hi</div>')
const div2 = dom.Create('<div>ha ha</div>')
dom.after(test, div1)
dom.wrap(test, div2)
console.log(div1)
const nodes = dom.empty(window.empty)
console.log(nodes)
dom.attr(test, 'title', 'i am frank')
const title = dom.attr(test, 'title')
console.log(`title:${title}`)
dom.text(test, 'how are you')
dom.style(test, { border: '1px solid red', color: 'blue' })
console.log(dom.style(test, 'border'))
dom.style(test, 'border', '1px solid black')
dom.class.add(test, 'red')
dom.class.remove(test, 'red')
console.log(dom.class.has(test, 'red'))
dom.on(test, 'click', fn => (console.log('点击了')))
let testDiv = dom.find('#siblings')[0]
console.log(dom.find('#s2', testDiv)[0])
console.log(dom.parent(s2))
console.log(dom.siblings(s2))
console.log(dom.siblings(dom.find('#s3')[0]))
console.log(dom.next(s2))
console.log(dom.previous(s2))
let t = dom.find('#travel')[0]
dom.each(dom.children(t), fn = (n) => { dom.style(n, 'border', '1px solid red') })
console.log(dom.index(s3))
